# Generated by Django 5.0.6 on 2024-06-05 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="realestate",
            name="predict_price",
        ),
    ]
